name: flutter_farm_map
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

#dependency_overrides:
#  intl: ^0.19.0

dependencies: 
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  extended_image: ^8.2.0
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flex_seed_scheme: ^2.0.0
  google_fonts: ^6.2.1
  # getwidget: ^4.0.0
  # get_storage: ^2.1.1
  shimmer: ^3.0.0
  # pull_to_refresh: ^2.0.0
  font_awesome_flutter: ^10.7.0
  # pull_to_refresh_notification: ^3.1.0
  # package_info_plus: ^7.0.0
  # flutter_staggered_grid_view: ^0.7.0
  # flutter_exit_app: ^1.1.2
  # share_plus: ^8.0.3
  # url_launcher: ^6.2.6
  # simple_fontellico_progress_dialog: ^0.3.0
  # uni_links: ^0.5.1
  # flutter_exif_rotation: ^0.5.1
  # image: ^4.1.7
  # image_cropper: ^5.0.1
  # image_picker: ^1.1.0
  # collection: ^1.18.0
  socket_io_client: ^2.0.3+1
  intl: ^0.19.0
  
  # google_places_for_flutter:
  #   git:
  #     url: https://github.com/wldevproject/google_places_for_flutter.git
  #     ref: main # branch name
  geocoding: ^3.0.0
  # geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  ripple_wave: ^0.1.4
  carousel_slider: ^4.2.1
  flutter_image_slideshow: ^0.1.6

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


