name: flutter_farm_map
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  extended_image: ^8.2.0
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flex_seed_scheme: ^2.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  socket_io_client: ^2.0.3+1
  intl: ^0.19.0
  
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  ripple_wave: ^0.1.4
  carousel_slider: ^4.2.1
  flutter_image_slideshow: ^0.1.6

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


